export interface Item {
    id: number;
    name: string;
    section: ItemTypeEnum;
    number: number;
    setName?: SetNameEnum;
};

export enum ItemTypeEnum {
    Swords = 0,
    Axes = 1,
    Maces = 2,
    Spears = 3,
    Bows = 4,
    Staves = 5,
    Shields = 6,
    Helms = 7,
    Armors = 8,
    Pants = 9,
    Gloves = 10,
    Boots = 11,
    Misc1 = 12,
    Misc2 = 13,
    Misc3 = 14,
    Misc4 = 15,
    Misc5 = 16,
    Misc6 = 20
}

export const ItemTypeDescriptions = {
    [ItemTypeEnum.Swords]: 'Swords and Claws',
    [ItemTypeEnum.Axes]: 'Axes',
    [ItemTypeEnum.Maces]: 'Maces and Scepters',
    [ItemTypeEnum.Spears]: 'Spears and Lances',
    [ItemTypeEnum.Bows]: 'Bows, Crossbows, Quivers and Guns',
    [ItemTypeEnum.Staves]: 'Staves, Sticks, Books and Orbs',
    [ItemTypeEnum.Shields]: 'Shields',
    [ItemTypeEnum.Helms]: 'Helms',
    [ItemTypeEnum.Armors]: 'Armors',
    [ItemTypeEnum.Pants]: 'Pants',
    [ItemTypeEnum.Gloves]: 'Gloves',
    [ItemTypeEnum.Boots]: 'Boots',
    [ItemTypeEnum.Misc1]: 'Misc items 1',
    [ItemTypeEnum.Misc2]: 'Misc items 2',
    [ItemTypeEnum.Misc3]: 'Misc items 3',
    [ItemTypeEnum.Misc4]: 'Misc items 4',
    [ItemTypeEnum.Misc5]: 'Misc items 5',
    [ItemTypeEnum.Misc6]: 'Misc items 6',
}

export enum SetNameEnum {
    None,
    'Bronze',
    'Dragon',
    'Pad',
    'Legendary',
    'Bone',
    'Leather',
    'Scale',
    'Sphinx',
    'Brass',
    'Plate',
    'Vine',
    'Silk',
    'Wind',
    'Spirit',
    'Guardian',
    'Storm Crow',
    'Black Dragon',
    'Dark Phoenix',
    'Grand Soul',
    'Holy Spirit',
    'Thunder Hawk',
    'Great Dragon',
    'Dark Soul',
    'Hurricane',
    'Red Spirit',
    'Light Plate',
    'Adamantine',
    'Dark Steel',
    'Dark Master',
    'Dragon Knight',
    'Venom Mist',
    'Sylphid Ray',
    'Volcano',
    'Sunlight',
    'Ashcrow',
    'Eclipse',
    'Iris',
    'Valiant',
    'Glorious',
    'Violent Wind',
    'Red Wing',
    'Ancient',
    'Demonic',
    'Storm Blitz',
    'Eternal Wing',
    'Titan',
    'Brave',
    'Phantom',
    'Destruction',
    'Seraphim',
    'Divine',
    'Royal',
    'Hades',
    'Succubus',
    'Lazy Wind',
    'Dark Devil',
    'Sticky',
    'Hell Night',
    'Ambition',
    'Sacred Fire',
    'Storm Jahad',
    'Piercing Grove',
    '[Lucky] Red Wing',
    'Atlans',
    'Phoenix Soul',
    'Stormwing',
    'Light Lord',
    'Magic Knight',
    'Robust',
    'Gru Hill',
    'Princie',
    'Hirat',
    'Sate',
    'Bloodangel Knight',
    'Bloodangel Wizard',
    'Bloodangel Elf',
    'Bloodangel Summoner',
    'Bloodangel Gladiator',
    'Bloodangel Lord',
    'Bloodangel Fighter',
    'Bloodangel Lancer',
    'Soul Knight',
    'Soul Wizard',
    'Soul Elf',
    'Soul Summoner',
    'Soul Gladiator',
    'Soul Lord',
    'Soul Fighter',
    'Soul Lancer',
    'Soul Amplifier Elf',
    'Soul Magic  Gladiator',
    'Rune Pad',
    'Rune Sphinx',
    'Rune Legendary',
    'Kanaz',
    'Rune Divine',
    'Rune Light',
    'Bloodangel Runist',
    'Darkangel Runist',
    '[Bound] Rune Legendary',
    'Holyangel Runist',
    'Soul Runist',
    'Blue Eye Runist',
    '[Bound] Dragon',
    '[Bound] Legendary',
    '[Bound] Guardian',
    '[Bound] Atlans',
    '[Bound] Adamantine',
    '[Bound] Red Winged',
    '[Bound] Storm Zahard',
    '[Bound] Princie',
    'Darkangel Knight',
    'Darkangel Wizard',
    'Darkangel Elf',
    'Darkangel Summoner',
    'Darkangel Gladiator',
    'Darkangel Lord',
    'Darkangel Fighter',
    'Darkangel Lancer',
    'Tigris',
    'Crimson Skull',
    'Grace',
    'Constant',
    'Holyangel Knight',
    'Holyangel Wizard',
    'Holyangel Elf',
    'Holyangel Summoner',
    'Holyangel Gladiator',
    'Holyangel Lord',
    'Holyangel Fighter',
    'Holyangel Lancer',
    'Bloodangel Amplifier Elf',
    'Darkangel Amplifier Elf',
    'Holyangel Amplifier Elf',
    'Bloodangel Magic Gladiator',
    'Darkangel Magic Gladiator',
    'Holyangel Magic Gladiator',
    'Blue Eye Knight',
    'Blue Eye Wizard',
    'Blue Eye Elf',
    'Blue Eye Summoner',
    'Blue Eye Gladiator',
    'Blue Eye Lord',
    'Blue Eye Fighter',
    'Blue Eye Lancer',
    'Blue Eye Amplifier Elf',
    'Blue Eye Magic Gladiator',
    'Slayer Red Wing',
    'Slayer',
    'Slayer Demonic',
    'Nightwing',
    'Fidelity',
    'Trace',
    'Bloodangel Slayer',
    'Darkangel Slayer',
    'Holyangel Slayer',
    'Soul Slayer',
    'Blue Eye Slayer',
    'Silver Heart Slayer',
    '[Lucky] Slayer',
    '[Lucky] Slayer Demonic',
    '[Bound] Slayer Demonic',
    'Silver Heart Knight',
    'Silver Heart Wizard',
    'Silver Heart Elf',
    'Silver Heart Summoner',
    'Silver Heart Gladiator',
    'Silver Heart Lord',
    'Silver Heart Fighter',
    'Silver Heart Lancer',
    'Silver Heart Amplifier Elf',
    'Silver Heart Magic Gladiator',
    'Silver Heart Runist',
    'Bloodangel Support Knight',
    'Darkangel Support Knight',
    'Holyangel Support Knight',
    'Soul Support Knight',
    'Blue Eye Support Knight',
    'Silver Heart Support Knight',
    'Leather Gunner',
    'Scale Gunner',
    'Round Gunner',
    'Frere',
    'Titan Gunner',
    'Stormbringer',
    'Bloodangel Gunner',
    'Darkangel Gunner',
    'Holyangel Gunner',
    'Soul Gunner',
    'Blue Eye Gunner',
    'Silver Heart Gunner',
    '[Bound] Frere',
    'Manticore Knight',
    'Manticore Wizard',
    'Manticore Elf',
    'Manticore Summoner',
    'Manticore Gladiator',
    'Manticore Lord',
    'Manticore Fighter',
    'Manticore Lancer',
    'Manticore Amplifier Elf',
    'Manticore Magic Gladiator',
    'Manticore Runist',
    'Manticore Slayer',
    'Manticore Support Knight',
    'Manticore Gunner',
    'Glimmer',
    'Light Ray',
    'Flash',
    'Magic Flare',
    'Bright',
    'Darjeeling',
    'Bloodangel Kundun',
    'Darkangel Kundun',
    'Holyangel Kundun',
    'Soul Kundun',
    'Blue Eye Kundun',
    'Silver Heart Kundun',
    'Manticore Kundun',
    '[Bound] Light Ray',
    'Mage Pad',
    'Mage Sphinx',
    'Mage Legendary',
    'Noble Pixie',
    'Finesse',
    'Geist',
    'Bloodangel Lemurian',
    'Darkangel Lemurian',
    'Holyangel Lemurian',
    'Soul Lemurian',
    'Blue Eye Lemurian',
    'Silver Heart Lemurian',
    'Manticore Lemurian',
    '[Bound] Mage Legendary',
    'Brilliant Knight',
    'Brilliant Wizard',
    'Brilliant Elf',
    'Brilliant Summoner',
    'Brilliant Gladiator',
    'Brilliant Lord',
    'Brilliant Fighter',
    'Brilliant Lancer',
    'Brilliant Amplifier Elf',
    'Brilliant Magic Gladiator',
    'Brilliant Runist',
    'Brilliant Slayer',
    'Brilliant Support Knight',
    'Brilliant Gunner',
}

export enum ExcOptionEnum {
    zenMana = 1,
    dsrLife = 2,
    refSpeed = 4,
    ddInc2 = 8,
    manaLvl20 = 16,
    hpEdr = 32
}

export const itemTypes: ItemTypeEnum[] = [
    ItemTypeEnum.Swords,
    ItemTypeEnum.Axes,
    ItemTypeEnum.Maces,
    ItemTypeEnum.Spears,
    ItemTypeEnum.Bows,
    ItemTypeEnum.Staves,
    ItemTypeEnum.Shields,
    ItemTypeEnum.Helms,
    ItemTypeEnum.Armors,
    ItemTypeEnum.Pants,
    ItemTypeEnum.Gloves,
    ItemTypeEnum.Boots,
    ItemTypeEnum.Misc1,
    ItemTypeEnum.Misc2,
    ItemTypeEnum.Misc3,
    ItemTypeEnum.Misc4,
    ItemTypeEnum.Misc5,
    ItemTypeEnum.Misc6
];